"""add_task_description

Revision ID: 3e996a857aa2
Revises: 21f6aac25b87
Create Date: 2025-11-28 11:39:51.521204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e996a857aa2'
down_revision = '21f6aac25b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
