"""make task deadline nullable

Revision ID: 5236453cafd3
Revises: e0cb15130b94
Create Date: 2025-11-21 11:08:11.563320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5236453cafd3'
down_revision = 'e0cb15130b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
