"""make deadline nullable

Revision ID: e0cb15130b94
Revises: 312771219d39
Create Date: 2025-11-21 11:06:22.320885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cb15130b94'
down_revision = '312771219d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'deadline',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'deadline',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
